### ISSUE TITLE
由4.0.2升级到4.0.3后出现错误

### ISSUE THREAD

**Issue by yugihuang** [overtrue/wechat#1081]
## 我用的环境

PHP 版本：7.1.9
overtrue/wechat 版本：4.0.3
是否使用了框架？框架名称：laravel 5.5

## 问题及现象
通过composer 由4.0.2升级到4.0.3后出现错误,  还原会4.0.2后正常.

日志信息如下:
[2017-12-26 15:41:39] LOCAL.ERROR: Call to undefined method EasyWeChat\Work\Base\Client::agent() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method EasyWeChat\\Work\\Base\\Client::agent() at /home/wwwroot/wework/vendor/overtrue/wechat/src/Work/Application.php:75)
[stacktrace]
#0 /home/wwwroot/wework/app/Contacts/Commands/FetchEmployee.php(37): EasyWeChat\\Work\\Application->__call('agent', Array)
#1 [internal function]: App\\Contacts\\Commands\\FetchEmployee->__construct()
#2 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): ReflectionClass->newInstanceArgs(Array)
#3 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('App\\\\Contacts\\\\Co...')
#4 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('App\\\\Contacts\\\\Co...', Array)
#5 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('App\\\\Contacts\\\\Co...', Array)
#6 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Console/Application.php(228): Illuminate\\Foundation\\Application->make('App\\\\Contacts\\\\Co...')
#7 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Console/Application.php(242): Illuminate\\Console\\Application->resolve('App\\\\Contacts\\\\Co...')
#8 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(317): Illuminate\\Console\\Application->resolveCommands(Array)
#9 /home/wwwroot/wework/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Foundation\\Console\\Kernel->getArtisan()
#10 /home/wwwroot/wework/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"}

**Comment by yugihuang** [comment]
没注意到4.0.3的文档修改了, 4.0.3每个agent需要单独配置.
