### ISSUE TITLE
小程序获取用户手机要点击两次获取按钮才能获取到用户电话号码

### ISSUE THREAD

**Issue by fncong** [overtrue/wechat#1293]
## 我用的环境

PHP 版本：7.1
overtrue/wechat 版本：4.0
框架名称：ThinkPHP 5.0

## 问题及现象
获取用户手机要点击两次获取按钮才能获取到用户电话号码
### php代码如下
![](https://muguaoss.oss-cn-beijing.aliyuncs.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180709223826.png?Expires=1531150725&OSSAccessKeyId=TMP.AQGSNMmxset1FZB6EJ513iUwNWD0rTc9jKHHADkpfLfhUuxQC0sXZxd8JG0pADAtAhUAirlji49RF6c5pkrZytXsMoytex8CFAU6SLg4yrjEFoSi_C-HEFUHAfNR&Signature=AuaOlmkyhXCr%2B3p7UJmfFCkX3Jo%3D)
### 小程序代码如下
![](https://muguaoss.oss-cn-beijing.aliyuncs.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180709224311.png?Expires=1531151041&OSSAccessKeyId=TMP.AQGSNMmxset1FZB6EJ513iUwNWD0rTc9jKHHADkpfLfhUuxQC0sXZxd8JG0pADAtAhUAirlji49RF6c5pkrZytXsMoytex8CFAU6SLg4yrjEFoSi_C-HEFUHAfNR&Signature=CeSrMzgGT8oS8%2FWrX%2F2kf6biC7E%3D)
### 报错信息如下
![](https://muguaoss.oss-cn-beijing.aliyuncs.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180709224608.png?Expires=1531151193&OSSAccessKeyId=TMP.AQGSNMmxset1FZB6EJ513iUwNWD0rTc9jKHHADkpfLfhUuxQC0sXZxd8JG0pADAtAhUAirlji49RF6c5pkrZytXsMoytex8CFAU6SLg4yrjEFoSi_C-HEFUHAfNR&Signature=DUkppOD5xd7LPXW5WgVsmcdJRkU%3D)

报错之后再点击一次就能正常解析到用户电话号码

**Comment by mingyoung** [comment]
图片看不到

**Comment by fncong** [comment]
PHP 代码如下
/**
     * 解析加密数据获取用户手机号码
     */
    public function getPhone($value='')
    {
        $app = Factory::miniProgram(WeChatConfig::load());
        $iv = $this->request->post("iv");
        $code = $this->request->post("code");
        $encrypted_data = $this->request->post("encrypted_data");

        $ret = $app->auth->session($code);
        $decryptedData = $app->encryptor->decryptData($ret['session_key'], $iv, $encrypted_data);
        $this->success("获取成功", ['phoneinfo' => $decryptedData]);
    }

小程序代码如下
getPhone:function(e){
    console.log(e);
    var that=this;
    wx.login({
      success: function(res) {
        if (res.code) {
          app.request('api/wxapp/getPhone',{encrypted_data:e.detail.encryptedData,iv:e.detail.iv,code:res.code},function(rsp,json){
            that.setData({ mobile: rsp.phoneinfo.phoneNumber});
          },function(rsp,json){
            app.info('发生错误！请重试');
          });
        }
      }
    });
  },

报错如下

**Comment by overtrue** [comment]
@fncong 请正确使用 markdown

**Comment by tinpont** [comment]
同样遇到这个问题。偶发性，大部分可以解密，少部分报"The given payload is invalid."。这个问题只存在于通过小程序获取手机号码授权解密。

**Comment by mingyoung** [comment]
注意你的 session_key 时效

tinpont <notifications@github.com>于2018年7月11日 周三上午10:49写道：

**Comment by forecho** [comment]
之前使用正常，最近也遇到这种问题，不知道怎么回事，有人知道怎么解决吗？

**Comment by forecho** [comment]
@fncong 我也遇到这个问题，现在解决了。主要是 JS 那边。获取 code 一定要在点击授权登录按钮之前。

![image](https://user-images.githubusercontent.com/1725326/44021215-d2bec5d6-9f16-11e8-9b66-b19a2e2bdeec.png)

**Comment by tinpont** [comment]
@oknixus

你现在的顺序应该是：
进入界面 -> 显示界面 -> 用户点击授权按钮 -> 调用 wx.login() -> 提交到服务器

这是错误的，应该改成以下顺序：
进入界面 -> wx.login() -> 显示界面 -> 用户点击授权按钮 -> 提交到服务器

**Comment by oknixus** [comment]
我的是正确的顺序！我目前只是在测试过程中使用，在小程序中，我是通过一个按钮调用login和授权接口的：
```
  getUserInfo: function() {
    wx.login({
        success(res){
            console.log('code：'+res.code)
        }
    })
      wx.getUserInfo({
          success: res => {
              console.log('iv：'+ res.iv)
              console.log('encryptedData：'+res.encryptedData)
          }
      })
  }
```
然后手动copy到接口（我的域名还没添加到小程序后台）中，再去执行解密。
我每次调用，都是上面那个错误，但是如果我去改一下那段代码，即使是改成这样：
```
        $decrypted = $this->pkcs7Unpad($decrypted);
        $decrypted = json_decode($decrypted, true);
```
连续尝试了三次，都是可以解密成功的，没有任何错误；
如果是这样，几乎每次都报这个错误，不明白为什么
```
        $decrypted = json_decode($this->pkcs7Unpad($decrypted), true);
```

**Comment by tinpont** [comment]
报错贴一下

**Comment by oknixus** [comment]
```
{"message":"The given payload is invalid.","status_code":500,"debug":{"line":45,"file":"\/usr\/share\/nginx\/html\/shuati\/vendor\/overtrue\/wechat\/src\/MiniProgram\/Encryptor.php","class":"EasyWeChat\\Kernel\\Exceptions\\DecryptException","trace":["#0 \/usr\/share\/nginx\/html\/shuati\/app\/Libraries\/MinaLibrary.php(76): EasyWeChat\\MiniProgram\\Encryptor->decryptData('+xC78xM7yVEvs3a...', 'G5kF060PudogCxa...', 'RUJWAAGM0Ew44m4...')","#1 \/usr\/share\/nginx\/html\/shuati\/app\/Http\/Controllers\/Api\/V1\/AuthController.php(48): App\\Libraries\\MinaLibrary->getUserInfo('+xC78xM7yVEvs3a...', 'G5kF060PudogCxa...', 'RUJWAAGM0Ew44m4...')","#2 [internal function]: App\\Http\\Controllers\\Api\\V1\\AuthController->login(Object(Dingo\\Api\\Http\\Request))","#3 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/container\/BoundMethod.php(29): call_user_func_array(Array, Array)","#4 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/container\/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()","#5 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/container\/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))","#6 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/container\/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)","#7 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(373): Illuminate\\Container\\Container->call(Array, Array)","#8 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(339): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)","#9 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(313): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\Api\\V1\\AuthController), 'login', Array)","#10 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(275): Laravel\\Lumen\\Application->callControllerAction(Array)","#11 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(255): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)","#12 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Dingo\\Api\\Http\\Request))","#13 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#14 \/usr\/share\/nginx\/html\/shuati\/vendor\/dingo\/api\/src\/Http\/Middleware\/PrepareController.php(45): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#15 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#16 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#17 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#18 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(102): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#19 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(410): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#20 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(256): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#21 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(230): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#22 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(164): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#23 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(413): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#24 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(166): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#25 \/usr\/share\/nginx\/html\/shuati\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Lumen.php(102): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#26 \/usr\/share\/nginx\/html\/shuati\/vendor\/dingo\/api\/src\/Routing\/Router.php(512): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#27 \/usr\/share\/nginx\/html\/shuati\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#28 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#29 \/usr\/share\/nginx\/html\/shuati\/vendor\/barryvdh\/laravel-cors\/src\/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#30 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(149): Barryvdh\\Cors\\HandlePreflight->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#31 \/usr\/share\/nginx\/html\/shuati\/app\/Http\/Middleware\/ChangeLocale.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#32 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(149): App\\Http\\Middleware\\ChangeLocale->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#33 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#34 \/usr\/share\/nginx\/html\/shuati\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#35 \/usr\/share\/nginx\/html\/shuati\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#36 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#37 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#38 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#39 \/usr\/share\/nginx\/html\/shuati\/vendor\/illuminate\/pipeline\/Pipeline.php(102): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#40 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(410): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#41 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(166): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#42 \/usr\/share\/nginx\/html\/shuati\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(107): Laravel\\Lumen\\Application->dispatch(NULL)","#43 \/usr\/share\/nginx\/html\/shuati\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#44 {main}"]}}
```

**Comment by oknixus** [comment]
![image](https://user-images.githubusercontent.com/4592706/50203268-e1864c80-039b-11e9-98ca-a9dfba8f2efb.png)
