### ISSUE TITLE
撤销订单接口报错：cURL error 52: Empty reply from server

### ISSUE THREAD

**Issue by oknixus** [overtrue/wechat#1303]
PHP 版本：7.1.19 fpm
overtrue/wechat 版本：
        "overtrue/laravel-wechat": "^4.0",

框架名称：lumen 5.5

## 问题及现象
在调用撤销订单`$app->reverse->byOutTradeNumber("商户系统内部的订单号（out_trade_no）");`时报错：
`cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

## 详细的错误信息：
[2018-07-17 18:04:22] lumen.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Kernel/Traits/HasHttpRequests.php(150): GuzzleHttp\Client->request('POST', 'secapi/pay/reve...', Array)
#14 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Kernel/BaseClient.php(84): EasyWeChat\Payment\Kernel\BaseClient->performRequest('secapi/pay/reve...', 'POST', Array)
#15 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Kernel/BaseClient.php(125): EasyWeChat\Payment\Kernel\BaseClient->request('secapi/pay/reve...', Array, 'post', Array)
#16 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Reverse/Client.php(63): EasyWeChat\Payment\Kernel\BaseClient->safeRequest('secapi/pay/reve...', Array)
#17 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Reverse/Client.php(29): EasyWeChat\Payment\Reverse\Client->reverse('201807171757135...', 'out_trade_no')
#18 /usr/share/nginx/html/mina/app/Libraries/WxPayLibrary.php(75): EasyWeChat\Payment\Reverse\Client->byOutTradeNumber('201807171757135...')
#19 /usr/share/nginx/html/mina/app/Http/Controllers/Api/V1/ConsumeController.php(73): App\Libraries\WxPayLibrary->revokeOrder('201807171757135...')
#20 [internal function]: App\Http\Controllers\Api\V1\ConsumeController->addOrder(Object(Dingo\Api\Http\Request))
#21 /usr/share/nginx/html/mina/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /usr/share/nginx/html/mina/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /usr/share/nginx/html/mina/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#24 /usr/share/nginx/html/mina/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#25 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\Container\Container->call(Array, Array)
#26 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#27 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Api\V1\ConsumeController), 'addOrder', Array)
#28 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\Lumen\Application->callControllerAction(Array)
#29 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(255): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#30 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Dingo\Api\Http\Request))
#31 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#32 /usr/share/nginx/html/mina/app/Http/Middleware/Authenticate.php(42): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#33 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#35 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#36 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/RateLimit.php(70): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#37 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Dingo\Api\Http\Middleware\RateLimit->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#39 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#40 /usr/share/nginx/html/mina/vendor/liyu/dingo-serializer-switch/src/SerializerSwitch.php(44): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#41 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Liyu\Dingo\SerializerSwitch->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#43 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#44 /usr/share/nginx/html/mina/vendor/palanik/lumen-cors/LumenCors.php(110): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#45 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): palanik\lumen\Middleware\LumenCors->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#47 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#48 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#49 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Dingo\Api\Http\Middleware\PrepareController->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#51 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#52 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#53 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#55 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(230): Laravel\Lumen\Application->handleFoundRoute(Array)
#56 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(164): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#57 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#58 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#59 /usr/share/nginx/html/mina/vendor/dingo/api/src/Routing/Adapter/Lumen.php(102): Laravel\Lumen\Application->dispatch(Object(Dingo\Api\Http\Request))
#60 /usr/share/nginx/html/mina/vendor/dingo/api/src/Routing/Router.php(512): Dingo\Api\Routing\Adapter\Lumen->dispatch(Object(Dingo\Api\Http\Request), 'v1')
#61 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#62 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(114): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#63 /usr/share/nginx/html/mina/vendor/palanik/lumen-cors/LumenCors.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#64 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): palanik\lumen\Middleware\LumenCors->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#65 /usr/share/nginx/html/mina/app/Http/Middleware/ChangeLocale.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#66 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): App\Http\Middleware\ChangeLocale->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#67 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#68 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#70 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#71 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#74 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#76 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#77 /usr/share/nginx/html/mina/public/index.php(28): Laravel\Lumen\Application->run()
#78 {main}  
[2018-07-17 18:04:57] lumen.INFO: select * from `users` where `users`.`id` = '19' and `users`.`deleted_at` is null limit 1  
[2018-07-17 18:04:57] lumen.INFO: select count(*) as aggregate from `courses` where `id` = '5' and ((`is_published` = '1' and `is_delete` = '0'))  
[2018-07-17 18:04:57] lumen.INFO: select `id`, `consume_sn`, `user_id`, `course_id`, `course_name`, `course_name` as `title`, `order_amount`, `paid_amount`, `discount`, `prepay_id`, `state`, `paid_time`, `created_at`, `updated_at` from `consumes` where `user_id` = '19' and `course_id` = '5' limit 1  
[2018-07-17 18:04:58] lumen.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /usr/share/nginx/html/mina/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Kernel/Traits/HasHttpRequests.php(150): GuzzleHttp\Client->request('POST', 'secapi/pay/reve...', Array)
#14 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Kernel/BaseClient.php(84): EasyWeChat\Payment\Kernel\BaseClient->performRequest('secapi/pay/reve...', 'POST', Array)
#15 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Kernel/BaseClient.php(125): EasyWeChat\Payment\Kernel\BaseClient->request('secapi/pay/reve...', Array, 'post', Array)
#16 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Reverse/Client.php(63): EasyWeChat\Payment\Kernel\BaseClient->safeRequest('secapi/pay/reve...', Array)
#17 /usr/share/nginx/html/mina/vendor/overtrue/wechat/src/Payment/Reverse/Client.php(29): EasyWeChat\Payment\Reverse\Client->reverse('201807171757135...', 'out_trade_no')
#18 /usr/share/nginx/html/mina/app/Libraries/WxPayLibrary.php(75): EasyWeChat\Payment\Reverse\Client->byOutTradeNumber('201807171757135...')
#19 /usr/share/nginx/html/mina/app/Http/Controllers/Api/V1/ConsumeController.php(73): App\Libraries\WxPayLibrary->revokeOrder('201807171757135...')
#20 [internal function]: App\Http\Controllers\Api\V1\ConsumeController->addOrder(Object(Dingo\Api\Http\Request))
#21 /usr/share/nginx/html/mina/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /usr/share/nginx/html/mina/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /usr/share/nginx/html/mina/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#24 /usr/share/nginx/html/mina/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#25 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\Container\Container->call(Array, Array)
#26 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#27 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\Api\V1\ConsumeController), 'addOrder', Array)
#28 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\Lumen\Application->callControllerAction(Array)
#29 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(255): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#30 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Dingo\Api\Http\Request))
#31 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#32 /usr/share/nginx/html/mina/app/Http/Middleware/Authenticate.php(42): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#33 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#35 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#36 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/RateLimit.php(70): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#37 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Dingo\Api\Http\Middleware\RateLimit->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#39 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#40 /usr/share/nginx/html/mina/vendor/liyu/dingo-serializer-switch/src/SerializerSwitch.php(44): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#41 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Liyu\Dingo\SerializerSwitch->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#43 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#44 /usr/share/nginx/html/mina/vendor/palanik/lumen-cors/LumenCors.php(110): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#45 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): palanik\lumen\Middleware\LumenCors->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#47 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#48 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#49 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Dingo\Api\Http\Middleware\PrepareController->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#51 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))
#52 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Dingo\Api\Http\Request))
#53 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#55 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(230): Laravel\Lumen\Application->handleFoundRoute(Array)
#56 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(164): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#57 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#58 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#59 /usr/share/nginx/html/mina/vendor/dingo/api/src/Routing/Adapter/Lumen.php(102): Laravel\Lumen\Application->dispatch(Object(Dingo\Api\Http\Request))
#60 /usr/share/nginx/html/mina/vendor/dingo/api/src/Routing/Router.php(512): Dingo\Api\Routing\Adapter\Lumen->dispatch(Object(Dingo\Api\Http\Request), 'v1')
#61 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))
#62 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(114): Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))
#63 /usr/share/nginx/html/mina/vendor/palanik/lumen-cors/LumenCors.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#64 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): palanik\lumen\Middleware\LumenCors->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#65 /usr/share/nginx/html/mina/app/Http/Middleware/ChangeLocale.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#66 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): App\Http\Middleware\ChangeLocale->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#67 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))
#68 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /usr/share/nginx/html/mina/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))
#70 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(149): Dingo\Api\Http\Middleware\Request->handle(Object(Dingo\Api\Http\Request), Object(Closure))
#71 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /usr/share/nginx/html/mina/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#74 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#76 /usr/share/nginx/html/mina/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#77 /usr/share/nginx/html/mina/public/index.php(28): Laravel\Lumen\Application->run()
#78 {main}

**Comment by aszx0413** [comment]
PHP 7.2 / easywechat ~4.0
同样因为撤消订单报这个错，会不会是SDK问题
在调用这个接口前还调用了queryByOutTradeNumber，可正常返回，所以排队了服务器和微信服务器的连接原因

**Comment by mingyoung** [comment]
@aszx0413 检查下证书是否配置正确
