### ISSUE TITLE
支付回调notify报错，日志内容如下

### ISSUE THREAD

**Issue by jayleco** [overtrue/wechat#1909]
## 我用的环境

* PHP 版本：7.3
* overtrue/wechat 版本：laravel-wechat5.0
* 是否使用了框架？框架名称：laravel7

## 问题及现象
使用easywechat支付什么的都很正常，但是我今天看了下日志发现有很多easywechat的报错，日志内容如下：
```log
[2020-07-31 20:44:37] local.ERROR: Invalid request XML. {"exception":"[object] (EasyWeChat\\Kernel\\Exceptions\\Exception(code: 400): Invalid request XML. at /www/wwwroot/wx.hahaha.vip/vendor/overtrue/wechat/src/Payment/Notify/Handler.php:143)
[stacktrace]
#0 /www/wwwroot/wx.hahaha.vip/vendor/overtrue/wechat/src/Payment/Notify/Paid.php(28): EasyWeChat\\Payment\\Notify\\Handler->getMessage()
#1 /www/wwwroot/wx.hahaha.vip/vendor/overtrue/wechat/src/Payment/Application.php(119): EasyWeChat\\Payment\\Notify\\Paid->handle(Object(Closure))
#2 /www/wwwroot/wx.hahaha.vip/app/Http/Controllers/VipController.php(347): EasyWeChat\\Payment\\Application->handlePaidNotify(Object(Closure))
#3 [internal function]: App\\Http\\Controllers\\VipController->notify(Object(Illuminate\\Http\\Request))
#4 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('notify', Array)
#6 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\VipController), 'notify')
#7 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#8 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#9 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#14 /www/wwwroot/wx.hahaha.vip/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}(Object(Illuminate\\Http\\Request))
#16 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/wx.hahaha.vip/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#21 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#23 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#24 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /www/wwwroot/wx.hahaha.vip/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /www/wwwroot/wx.hahaha.vip/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /www/wwwroot/wx.hahaha.vip/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#41 /www/wwwroot/wx.hahaha.vip/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#42 {main}
"} 
```

**Comment by jayleco** [comment]
该错误日志时间对应的的nginx日志信息
```
59.36.132.240 - - [31/Jul/2020:20:14:17 +0800] "GET http://wx.hahaha.vip/api/user/myorder?paid_at%3D1%26page%3D1 HTTP/1.1" 200 94 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0"
182.254.52.17 - - [31/Jul/2020:20:44:37 +0800] "GET http://wx.hahaha.vip/api/wechat-pay/notify/buy-vip HTTP/1.1" 500 593659 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0"
61.129.10.43 - - [31/Jul/2020:20:58:23 +0800] "GET /home?pid=124025598570 HTTP/1.1" 302 1398 "-" "Mozilla/5.0 (Linux; Android 9; ANE-AL00 Build/HUAWEIANE-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045227 Mobile Safari/537.36 MMWEBID/1988 MicroMessenger/7.0.17.1720(0x27001137) Process/tools WeChat/arm64 NetType/WIFI Language/zh_CN ABI/arm64"

```

**Comment by overtrue** [comment]
一般来讲，支付回调接口是公开的，也就可能存在黑客故意模拟微信推送请求来尝试攻击，所以你可以在逻辑里加日志，一旦有报错，记录请求的 XML 用于验证。

**Comment by vic091** [comment]
启动swoole 后，`        try {

            $message = XML::parse(strval($this->app['request']->getContent()));
        } catch (\Throwable $e) {
            throw new Exception('Invalid request XML: '.$e->getMessage(), 400);
        }`

这个地方抛异常，解析不了

**Comment by overtrue** [comment]
非 fpm 模式请自行解决哈

vic091 <notifications@github.com>于2020年10月23日 周五上午7:27写道：

**Comment by panjm** [comment]
$request = ApplicationContext::getContainer()->get(RequestInterface::class);
$message = XML::parse(strval($request->getBody()));
