### ISSUE TITLE
xampp下js->config报错

### ISSUE THREAD

**Issue by zuoa** [overtrue/wechat#366]
## xampp环境调试调试

PHP 版本：5.6.15
overtrue/wechat 版本：3.0

## 问题及现象
调用
```
wx.config(<?php echo $js->config(array('onMenuShareQQ', 'onMenuShareWeibo'), true, true, false) ?>);
```

输出错误：
```
    wx.config(<br />
<b>Fatal error</b>:  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in F:\xampp\htdocs\airimos-wechat\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 F:\xampp\htdocs\airimos-wechat\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 F:\xampp\htdocs\airimos-wechat\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 F:\xampp\htdocs\airimos-wechat\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 F:\xampp\htdocs in <b>F:\xampp\htdocs\airimos-wechat\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php</b> on line <b>187</b><br />

```

**Comment by zuoa** [comment]
找到说明了

https://easywechat.org/docs/zh-cn/troubleshooting.html
