### ISSUE TITLE
PHP Fatal error: Uncaught HttpException

### ISSUE THREAD

**Issue by apm1467** [overtrue/wechat#517]
## 我用的环境

nginx/1.10.0 (Ubuntu)
PHP 7.0.8
overtrue/wechat 版本：3.1

## 问题及现象

按照官方文档在服务器上部署 server.php 后，使用

``` 
php server.php
```

命令直接运行，得到报错：

```
PHP Fatal error:  Uncaught EasyWeChat\Core\Exceptions\HttpException: invalid openid hint: [YTFzja0249ge10] in /var/www/html/vendor/overtrue/wechat/src/Core/AbstractAPI.php:235
Stack trace:
#0 /var/www/html/vendor/overtrue/wechat/src/Core/AbstractAPI.php(135): EasyWeChat\Core\AbstractAPI->checkAndThrow(Array)
#1 /var/www/html/vendor/overtrue/wechat/src/Notice/Notice.php(176): EasyWeChat\Core\AbstractAPI->parseJSON('json', Array)
#2 /var/www/html/server.php(40): EasyWeChat\Notice\Notice->send()
#3 {main}
  thrown in /var/www/html/vendor/overtrue/wechat/src/Core/AbstractAPI.php on line 235
```

附上 server.php 内容：

```
<?php
    include __DIR__ . '/vendor/autoload.php';
    use EasyWeChat\Foundation\Application;
    $options = [
        'debug'  => true,
        'app_id' => '', // 公众号信息隐去
        'secret' => '',
        'token'  => '',
        'aes_key' => '',
        'log' => [
            'level' => 'debug',
            'file'  => '/tmp/test.log', // 绝对路径
        ],

        //...
    ];
    $app = new Application($options);
    $server = $app->server;

    $server->setMessageHandler(function ($message) {
        return "您好！欢迎关注我!";
    });

    $notice = $app->notice;
    $userId = 'apm1467';
    templateId = 'OPENTM400096976';
    $url = '';
    $color = '#FF0000';
    $data = array(
         "first"  => "您好，您有新的余额变动",
         "keyword1"   => "今天",
         "keyword2"  => "39.8元",
         "keyword3"  => "39.8元",
         "remark" => "欢迎再次购买！",
        );

    $result = $notice->uses($templateId)->withUrl($url)->andData($data)->andReceiver($userId)->send();
    var_dump($result);

    $response = $server->serve();
    $response->send(); 
?>

**Comment by overtrue** [comment]
```
invalid openid
```
