### ISSUE TITLE
在新浪SAE平台上的部署问题

### ISSUE THREAD

**Issue by baidut** [overtrue/wechat#63]
```
Fatal error: Uncaught exception 'Overtrue\Wechat\Exception' with message '
[Wechat]读取输入失败，请在 php.ini 中打开 always_populate_raw_post_data=On' 
in /data1/www/htdocs/152/a327/1/third_party/Wechat/Server.php:200 
Stack trace: #0 /data1/www/htdocs/152/a327/1/third_party/Wechat/Server.php(160): 
Overtrue\Wechat\Server->prepareInput() #1 /data1/www/htdocs/152/a327/1/wechat.php(20): 
Overtrue\Wechat\Server->serve() #2 {main} thrown in third_party/Wechat/Server.php on line 200
```

新浪的SAE下开发有一定限制，不能修改php.ini 想要部署在SAE上有解决的办法么？

**Comment by overtrue** [comment]
@baidut 请问是用的什么方式在访问。

**Comment by baidut** [comment]
感谢回复！是这样的，按照说明下载了最新的2.0.27版本，上传到SAE的服务器上后，
代码如下
```
<?php
require __DIR__ . "/autoload.php";

use Overtrue\Wechat\Server;
use Overtrue\Wechat\Message;

$appId          = 'XXX'; 
$token          = 'XXX'; 
$encodingAESKey = 'XXX'; // 可选
$server = new Server($appId, $token, $encodingAESKey);

$server->serve();
```
微信验证token失败，于是就直接用浏览器访问了一下这个页面，出现上面的出错信息，可能是SAE的服务器限制问题，不知道能不能解决

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/releases/tag/2.0.28

**Comment by cos800** [comment]
所以是不支持SAE喽？
